main: me.tdvne.chatclear.main
name: ChatClear
description: A simple spigot/bukkit plugin to clear chat modernly & effectively
authors:
 - tdvne
version: 1.0-SNAPSHOT
website: https://edater.dev
commands:
  chatclear:
    description: Clears the chat
    aliases: [cc, clearchat]
