main: me.tdvne.main
name: ChatClear
description: A simple yet effective way to clear chat
authors:
 - tdvne
version: 1.0-SNAPSHOT
commands:
  chatclear:
    description: Clears the chat
    aliases: [cc, clearchat]
